data_config:
    filename: pkl_name     # name of the .pkl with the dataset --> pkl_name.pkl
    name: NameOfTask     # name of the directory name for the task
    im_size: 128     # target size of the images (128x128)
    im_ch: 3      # channels of the images
    num_classes: 10     # task number of classes
    save_data_summary: true     # wether to save a summary of the data

train_config:
    batch_size: 64
    n_epochs: 40
    augmentation_probs:     # probabilities of each modality of augmentation for the training set
        gaussian: 0.2
        s&p: 0.1
        blur: 0.2
        hflip: 0.5
        vflip: 0.5
        rotate: 0.3
    lr: 0.0001
    model_config:     # Configuration layout for the CNN model
        down_ch:     # output channels of each down block
          - 16
          - 16
          - 32
          - 64
          - 128
        layers:     # number of layers in each down block 
          - 1
          - 2
          - 3
          - 3
        head_features:     # classification head hidden layers size
          - 1024
          - 512
          - 256
    model_config:      # Configuration layout for the ViT model
        n_heads: 8
        head_dim: 64
        emb_dim: 128
        attn_drop: 0.1
        ff_dim: 256
        ff_drop: 0.1
        n_layers: 6
        patch_height: 16
        patch_width: 16
        patch_emb_drop: 0.1
